### ISSUE TITLE
mistake in docker compose on readme

### ISSUE THREAD

**Issue by DragonHeart69** [lingarr-translate/lingarr#1]
On README.md, there is an mistake in your docker compose section:

```
libretranslate:
    image: libretranslate:latest
    container_name: libretranslate
```

This should be changed to:
```
libretranslate:
    image: libretranslate/libretranslate:latest
    container_name: libretranslate
```

**Comment by rowanfuchs** [comment]
I've set it to `libretranslate:latest` as you build the image locally, if you set it to libretranslate/libretranslate:latest you receive an image that doesn't have the languages installed.

**Comment by DragonHeart69** [comment]
Thank you for telling me this. I have to learn to read everything instead of just picking out the docker compose.

**Comment by rowanfuchs** [comment]
No problem, thank you for trying out the translator. I hope it is as usefull for you as it is for me.
