### ISSUE TITLE
How to use from command

### ISSUE THREAD

**Issue by eduardopventura** [lingarr-translate/lingarr#11]
Is there a way to run the translation by command line without the ui?
if has, whats the parameters and command?

**Comment by rowanfuchs** [comment]
Absolutely, you see the route /translate here:
https://github.com/lingarr-translate/lingarr/blob/main/lingarr_api/src/routes/api.routes.ts
and the needed format is in the controller:
https://github.com/lingarr-translate/lingarr/blob/main/lingarr_api/src/services/translate.service.ts
