### ISSUE TITLE
Multiple Subtitles Translation?

### ISSUE THREAD

**Issue by midn87** [lingarr-translate/lingarr#12]
Thank you for your efforts.
It would be more useful if you could make it translate multiple subtitles at once. It would take forever to translate 10 or 20 subtitles one by one.

**Comment by rowanfuchs** [comment]
With the latest [Release 0.9.0](https://github.com/lingarr-translate/lingarr/releases/tag/0.9.0) you can add a max concurrency and set the amount of automated translations to run. Thank you very much for your feedback and suggestion!
