### ISSUE TITLE
feat: Use Local LLMs to translate subtitles

### ISSUE THREAD

**Issue by adan89lion** [lingarr-translate/lingarr#13]
I'm running Ollama with multiple LLMs, and some multilingual models (like Gemma 27b and Command-R 32b) are quite capable of translating texts naturally and smoothly. I'm currently using [Subtitle Edit](https://github.com/SubtitleEdit/subtitleedit) with Ollama to translate my subtitles. Is it possible to integrate Ollama or other LLM enpoint to lingarr's backend?

**Comment by rowanfuchs** [comment]
Sounds good, I am definitely open to try. Are you using docker or their desktop app?

**Comment by rowanfuchs** [comment]
I've moved the feature request to the [discussions](https://github.com/lingarr-translate/lingarr/discussions/19)
