### ISSUE TITLE
ENV in docker compose

### ISSUE THREAD

**Issue by DragonHeart69** [lingarr-translate/lingarr#2]
With the copied docker compose I get the following error:

`Error sending request to LibreTranslate API: Failed to parse URL from "http://libretranslate:5000"/translate`

I modified my docker compose to:

```
    environment:
      LIBRETRANSLATE_API: http://libretranslate:5000
```

**Comment by rowanfuchs** [comment]
That is indeed the case, thanks a lot for pointing that out!
