### ISSUE TITLE
Can you use it without linking Sonarr and Radarr library ?

### ISSUE THREAD

**Issue by a-camacho** [lingarr-translate/lingarr#25]
Hi,

Can I use lingarr without linking said apps ?
I tried deploying it to docker, creating a movie folder in the /movies folder.

I have `/app/media/movies/Movie Name (movie-year)/Movie Name (movie-year).en.srt` but nothing happens.

Thank you very much

**Comment by rowanfuchs** [comment]
Lingarr only works when integrated with Sonarr and Radarr, however if you would like translate functionality without those apps I'd advise giving this discussion an upvote:

https://github.com/lingarr-translate/lingarr/discussions/20
