### ISSUE TITLE
Enhancement: Parse .hi also

### ISSUE THREAD

**Issue by karserasl** [lingarr-translate/lingarr#26]
Hey

First thanks for the amazing work.

I'm seeing that lingarr is translating episodes/movies when it shouldnt, since languages are satisfied, but its a .hi subtitles
for ex.

![{DD634F64-BF73-4518-8324-EB9AFCE675A7}](https://github.com/user-attachments/assets/6fb3e0b7-e7f4-4585-8d9c-60f8f8d331a8)
![{492372E4-2337-4906-90C4-01FC289D5286}](https://github.com/user-attachments/assets/5f094a97-c33e-44dd-bf59-071a20b7aebd)

As an enhancement, it should become more intelligent about when it is needed to translate or not (maybe even ffprobe the actual video to see the embedded subs)

**Comment by rowanfuchs** [comment]
Thank you for the idea, this will definitely added, I've added a freature request under https://github.com/lingarr-translate/lingarr/discussions/27 

I will have a look into ffprobe as well.
