### ISSUE TITLE
[feature] extract embedded subtitles [bulk]

### ISSUE THREAD

**Issue by ramonskie** [lingarr-translate/lingarr#29]
it would be a really nice feature to extract the embedded subtitles in bulk.

i currently do this from bazarr with the embedded subtitles provider and then translate that.
and then delete the extracted subtitle. as its really annoying that it shows up 2 times (embedded and extracted) in subtitle picker
but its painful as its all manual labor for now.

**Comment by rowanfuchs** [comment]
Subtitle extraction is on the optional roadmap already, however as Bazarr has this functionality I am still debating the need.
