### ISSUE TITLE
Error when booting the docker-container

### ISSUE THREAD

**Issue by Vince0511** [lingarr-translate/lingarr#38]
### Describe the problem

Hi There,
First of all I want to thank you for the effort of creating this piece of art. Thank you!
I've installed the containers by dockercompose, 

> services:
  lingarr:
    image: lingarr/lingarr:latest
    container_name: lingarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    ports:
      - 9876:8080
    volumes:
      - /home/vincent/docker/appdata/lingarr/data:/config
      - /home/vincent/Multimedia/movies:/movies
      - /home/vincent/Multimedia/tv-series:/tv-series
      - /home/vincent/Multimedia/tv-shows:/tv-shows
      - /home/vincent/Downloads:/Downloads
      - /mnt/newmedia:/mnt/newmedia
    restart: unless-stopped
    networks:
      - lingarr
  libretranslate:
    container_name: libretranslate
    image: libretranslate/libretranslate:latest
    restart: unless-stopped
    environment:
      - LT_LOAD_ONLY=en,nl,sw  # Important, replace with your preferred languages
    ports:
      - 5000:5000
    volumes:
      - /home/vincent/docker/appdata/libretranslate/config:/home/libretranslate/.local/share/argos-translate
    networks:
      - lingarr
    healthcheck:
      test: ["CMD-SHELL", "./venv/bin/python scripts/healthcheck.py"]
networks:
  lingarr:

Unfortunally I recieve the following.
> PermissionError: [Errno 13] Permission denied: '/home/libretranslate/.local/share/argos-translate/packages'

There's something I'm missing or just unable to see. Can anyone guide me in the right direction?

**Comment by Vince0511** [comment]
When I delete the dot (.) in the path, it works well. So my user didn't had enough permissions.
After that, everything looks like its working.

**Comment by mareczek82** [comment]
I had same problem. LibreTranslate container couldnt start with same  error. 
After deleting dot in "/home/libretranslate/.local/share/argos-translate/packages" container started, i can use gui, and paste text of subtitles to translate, but ligarr doesn't translate subtitles. translation jobs are waiting.
