### ISSUE TITLE
 Unknown source language

### ISSUE THREAD

**Issue by aristofeles** [lingarr-translate/lingarr#40]
### Describe the problem

As a test I extracted a included subtitle from a tv serie - re resulting file was TVSHOW.2024.S01E02.HDR.2160p.WEB.H265-SuccessfulCrab_track3_[eng].srt
From this file I created 3 files, the original,  TVSHOW.2024.S01E02.HDR.2160p.WEB.H265-SuccessfulCrab_[eng].srt and  TVSHOW.2024.S01E02.HDR.2160p.WEB.H265-SuccessfulCrab.srt

Only the third file appeared on lingarr, so I assume that the name of the subtitle must match the file name (ok, this is normal). But the subtitle keeps on the unknow language (is this the error?) and, when I try to force the translation, I see this on the logs;

[2024-12-26 16:32:41] [Error] Hangfire.AutomaticRetryAttribute: Failed to process the job '20': an exception occurred.
System.ArgumentException: Unknown source language. (Parameter 'fromLanguage')

![vivaldi_9YB0IcHdmJ](https://github.com/user-attachments/assets/b2ffb57c-7afb-429f-af14-5171a56db9f5)

![vivaldi_WtfiJK60AV](https://github.com/user-attachments/assets/5a88f6a2-426a-48ed-8dc8-3eeda43b5aef)

**Comment by jaycedk** [comment]
Try renaming TVSHOW.2024.S01E02.HDR.2160p.WEB.H265-SuccessfulCrab_track3_[eng].srt
to TVSHOW.2024.S01E02.HDR.2160p.WEB.H265-SuccessfulCrab_track3_.en.srt

**Comment by rowanfuchs** [comment]
What @jaycedk states is indeed the case, the name requires a subtitle language code according to 639-2 or 639-3 standards, if movies or series aren't found this could be an unsupported folder structure i.e. series without season segmentation or an incorrect volume configuration within docker. You would also need Sonarr and Radarr to provide folder and meta data to Lingarr.

**Comment by aristofeles** [comment]
closed
