### ISSUE TITLE
Brazilian Portuguese available for selection, but does not work

### ISSUE THREAD

**Issue by lucianor** [lingarr-translate/lingarr#5]
lingarr has the option to translate to Brazilian Portuguese in the dropdown. However, LibreTranslate only accepts pt and not pt-br. If Brazilian Portuguese is selected, it generates a subtitles with empty translations.

Fix is to remove Brazilian Portuguese from the select menu.

**Comment by rowanfuchs** [comment]
Thank you, I will remove it from the next version.

**Comment by rowanfuchs** [comment]
Thank you, I've merged your pull request and I will make sure it's removed in the next release too.
